version: '3.8'

services:
  app:
    build: .
    container_name: bookshop_be_app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/bookshop_db?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
      - base_url=https://vps.hieuvinhbook-shop.id.vn
      - base.url.FE=https://hieuvinh-book.vercel.app
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: bookshop_be_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookshop_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      retries: 10
      start_period: 10s

volumes:
  db_data:
